feat(helm): expose service type value
Jont828/cluster-api-visualizer pull request #56
Opened 2024-10-02 19:58 UTC by sl1pm4t

This adds support for specifying the service type in helm values.

2024-11-19 23:36 UTC, Jont828 requested changes
Thanks for the contribution! Just one minor nit and we're good to go. @sl1pm4t

2024-11-19 23:36 UTC, Jont828 commented on helm/cluster-api-visualizer/values.yaml
> +  type: ClusterIP
Could you add a newline?

2024-11-20 19:37 UTC, sl1pm4t commented on helm/cluster-api-visualizer/values.yaml
> +  type: ClusterIP
```suggestion
  type: ClusterIP

```

2024-11-25 21:46 UTC, Jont828 approved these changes

2024-11-25 21:46 UTC, merged

2024-11-25 21:46 UTC, Jont828 commented
Thanks!